### PR TITLE
Update test.txt

### PR DESCRIPTION
**Pull request by gtondello**
Testing a new PR

### CODE REVIEW

**Comment by gtondello** [comment]
Testing a **comment**.

`const comment = 'comment';`

**Comment by testguy12348** [comment]
test comment

**Comment by testguy12348** [comment]
test long comment
1
2
3
4
5

**Comment by testguy12348** [comment]
another test comment

**Comment by testguy12348** [comment]
third test comment

**Comment by testguy12348** [comment]
test comment

**Comment by testguy12348** [comment]
LGTM

**Comment by testguy12348** [comment]
test comment

**Comment by testguy12348** [comment]
test

**Comment by testguy12348** [comment]
comment

**Comment by testguy12348** [comment]
another comment

**Comment by testguy12348** [comment]
comment

**Pull request merged**
